import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <head>
        {/* Inline theme script to avoid flash of incorrect theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
            try {
        const stored = localStorage.getItem('theme');
        let shouldDark = true; // default to dark
        if (stored === 'light') shouldDark = false;
        if (stored === 'dark') shouldDark = true;
        document.documentElement.classList.toggle('dark', shouldDark);
            } catch {}
          `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
